apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordsmith-front.fullname" . }}
  labels:
    app: {{ include "wordsmith-front.name" . }}
    chart: {{ include "wordsmith-front.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "wordsmith-front.name" . }}
{{- if .Values.service.selectByRelease }}
    release: {{ .Release.Name }}
{{- end }}
